// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEv-FvzQq4p1GPFV6XQJmp_Ad3rzw7IbU',
    appId: '1:829161651919:web:ef54de4219f1f46fea81ba',
    messagingSenderId: '829161651919',
    projectId: 'chemeet-5c4a2',
    authDomain: 'chemeet-5c4a2.firebaseapp.com',
    storageBucket: 'chemeet-5c4a2.firebasestorage.app',
    measurementId: 'G-Y4434LZMFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu29RO1-gvZuMPTcxFhsDnLtxGyNc_ZyI',
    appId: '1:829161651919:android:6336cefbbc801bf7ea81ba',
    messagingSenderId: '829161651919',
    projectId: 'chemeet-5c4a2',
    storageBucket: 'chemeet-5c4a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXVyfX5vlxuMi2ytCuKQTzSa8ZUW_kwCk',
    appId: '1:829161651919:ios:ef819712e92a5ad8ea81ba',
    messagingSenderId: '829161651919',
    projectId: 'chemeet-5c4a2',
    storageBucket: 'chemeet-5c4a2.firebasestorage.app',
    iosBundleId: 'com.example.chemeet',
  );

}